In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("Recommendation System.csv")

In [3]:
data

,Timestamp,Name,Roll No,Class,Stream,Higher_Studies,Research,GATE,GRE,DataScience,...,IoT,ImageAnalysis,InterdisciplinaryKnowledge,RecentTechnologies,Job,Marks,ReadingElective1,ReadingElective2,DisciplineElective1,DisciplineElective2
0,2023/01/20 8:56:32 PM GMT+5:30,Pranjal,2016227,Btech cs section B,CS,No,No,No,No,No,...,No,No,No,No,Yes,Yes,2,1,7,1
1,2023/01/20 8:57:28 PM GMT+5:30,Shreyasi Sri,2016281,B.tech CS 3rd year,CS,Yes,No,No,No,No,...,No,No,No,Yes,No,No,5,6,6,3
2,2023/01/20 8:58:01 PM GMT+5:30,Muskan Gupta,2016198,Btech cs 6sem,CS,No,No,No,No,Yes,...,No,No,No,Yes,Yes,No,6,1,8,0
3,2023/01/20 9:05:09 PM GMT+5:30,Prabhuta Chaudhary,2016223,BTech CS B,CS,Yes,Yes,Yes,No,No,...,Yes,No,No,Yes,No,No,0,5,4,0
4,2023/01/20 9:06:37 PM GMT+5:30,Pooja Sharma,2016222,BTech CS B,CS,No,No,No,No,Yes,...,Yes,Yes,Yes,Yes,No,No,0,6,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,2023/02/19 12:02:09 PM GMT+5:30,Anshita Sharma,2016106,B.tech(CS)3rd year,CS,Yes,No,Yes,No,No,...,No,Yes,Yes,No,No,No,4,0,2,0
129,2023/02/19 1:15:31 PM GMT+5:30,Aritri,2016120,Btech,CS,Yes,No,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,No,6,0,4,2
130,2023/02/19 6:39:17 PM GMT+5:30,Raj Shree Bansal,2016242,BTECH,CS,Yes,No,No,Yes,No,...,No,No,No,Yes,Yes,Yes,6,2,8,7
131,2023/02/19 8:03:49 PM GMT+5:30,Kavya Bhagat,2016173,B.Tech CSE 3rd year,CS,Yes,No,No,Yes,No,...,Yes,No,Yes,No,No,No,4,5,4,6
132,2023/02/19 11:00:29 PM GMT+5:30,ANKITA,2016104,BTECH CS 6 SEMESTER,CS,Yes,No,Yes,Yes,No,...,Yes,Yes,Yes,Yes,No,No,0,6,4,2

In [4]:
data=data.drop(['Timestamp','Name','Roll No','Class','Stream'],axis=1)

In [5]:
data

,Higher_Studies,Research,GATE,GRE,DataScience,Artificial_Intelligence,MachineLearning,Blockchain,Cryptography,IoT,ImageAnalysis,InterdisciplinaryKnowledge,RecentTechnologies,Job,Marks,ReadingElective1,ReadingElective2,DisciplineElective1,DisciplineElective2
0,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,Yes,2,1,7,1
1,Yes,No,No,No,No,No,No,No,No,No,No,No,Yes,No,No,5,6,6,3
2,No,No,No,No,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,6,1,8,0
3,Yes,Yes,Yes,No,No,Yes,Yes,Yes,No,Yes,No,No,Yes,No,No,0,5,4,0
4,No,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,0,6,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,Yes,No,Yes,No,No,Yes,Yes,Yes,No,No,Yes,Yes,No,No,No,4,0,2,0
129,Yes,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,6,0,4,2
130,Yes,No,No,Yes,No,Yes,Yes,No,No,No,No,No,Yes,Yes,Yes,6,2,8,7
131,Yes,No,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,No,No,4,5,4,6
132,Yes,No,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,0,6,4,2

In [6]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [7]:
new_data=data

In [8]:
new_data['Higher_Studies']=lb.fit_transform(new_data['Higher_Studies'])
new_data['Research']=lb.fit_transform(new_data['Research'])
new_data['GATE']=lb.fit_transform(new_data['GATE'])
new_data['GRE']=lb.fit_transform(new_data['GRE'])
new_data['DataScience']=lb.fit_transform(new_data['DataScience'])
new_data['Artificial_Intelligence']=lb.fit_transform(new_data['Artificial_Intelligence'])
new_data['MachineLearning']=lb.fit_transform(new_data['MachineLearning'])
new_data['Blockchain']=lb.fit_transform(new_data['Blockchain'])
new_data['Cryptography']=lb.fit_transform(new_data['Cryptography'])
new_data['IoT']=lb.fit_transform(new_data['IoT'])
new_data['ImageAnalysis']=lb.fit_transform(new_data['ImageAnalysis'])
new_data['InterdisciplinaryKnowledge']=lb.fit_transform(new_data['InterdisciplinaryKnowledge'])
new_data['RecentTechnologies']=lb.fit_transform(new_data['RecentTechnologies'])
new_data['Job']=lb.fit_transform(new_data['Job'])
new_data['Marks']=lb.fit_transform(new_data['Marks'])

In [9]:
x=new_data[['Higher_Studies','Research','GATE','GRE','DataScience','Artificial_Intelligence','MachineLearning','Blockchain','Cryptography','IoT','ImageAnalysis','InterdisciplinaryKnowledge','RecentTechnologies','Job','Marks']]
y=new_data[['DisciplineElective1','DisciplineElective2']]

In [10]:
x.shape

(133, 15)

In [11]:
y.shape

(133, 2)

In [12]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.1,random_state=42)

In [13]:
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier(n_estimators=100, random_state=42)
clf.fit(xtrain, ytrain)

ExtraTreesClassifier(random_state=42)

In [14]:
ypred=clf.predict_proba(xtest)

In [15]:
clf.predict([[0,0,0,0,0,0,0,0,0,0,0,0,0,1,1]])

C:\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

array([[7, 1]], dtype=int64)

In [16]:
output=clf.predict([[1,0,1,1,0,1,1,1,1,1,1,1,1,0,0]])
output

C:\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

array([[4, 2]], dtype=int64)

In [17]:
import pickle

In [18]:
with open("modelRE.pkl", "wb") as f:
    pickle.dump(clf,f)